#!/usr/bin/env bash
# Clean up after installation.

# Source utility functions.
SCRIPTSDIR="$(dirname "$(pwd)/$0")"
. "$SCRIPTSDIR/utils"

# Remove the config backup directory.
BAKDIR="$HOME/.dotfilesbak"
Q="Remove config backup directory '$BAKDIR'? [y/n] "
if ask "$Q"; then
  rm -rvf "$BAKDIR"
fi
