#!/usr/bin/env bash
# Thunderbird software/config installation module.

# Source utility functions.
SCRIPTSDIR="$(dirname "$(pwd)/$0")"
. "$SCRIPTSDIR/utils"

# Software installation.
software() {
  Q="Install Thunderbird and Lightning? [y/n] "
  if ask "$Q"; then
    PKG="thunderbird lightning calendar-google-provider"
    sudo apt install $PKG
  fi
}

# Config installation.
config() {
  return
}
