#!/usr/bin/env bash
# TAVI-pp software/config installation module.

# Source utility functions.
SCRIPTSDIR="$(dirname "$(pwd)/$0")"
. "$SCRIPTSDIR/utils"

# Software installation.
software() {
  Q="Install TAVI-pp? [y/n] "
  if ask "$Q"; then
    read -rp "Username for 'https://net.feops.com': " USER
    REP="https://$USER@net.feops.com/gitlab/feops/TAVI-pp.git"
    TGT="$HOME/Documents/heartguide/tavi-pp"
    install_git_repo "$REP" "$TGT"
  fi
}

# Config installation.
config() {
  Q="Install TAVI-pp config? [y/n] "
  if ask "$Q"; then
    install_symlink_to ".config/pyformex/tavipp.conf"
  fi
}
