#!/usr/bin/env bash

# Source utility functions.
SCRIPTSDIR="$(dirname "$(pwd)/$0")"
. "$SCRIPTSDIR/utils"

# Install bashrc.
install_symlink_to ".bashrc"
install_symlink_to ".bash_aliases"
install_symlink_to ".bash_prompt"

# Install SSH config.
install_symlink_to ".ssh/config"

# Install xfce4-terminal config.
install_symlink_to ".config/xfce4/terminal/terminalrc"

# Install sshfs.
install_apt "sshfs" "sshfs"

# Install mlocate.
install_apt "mlocate" "mlocate"

# Install Git and its config, and gitk.
install_apt "gitk" "git gitk"
install_symlink_to ".gitconfig"

# Install PCManFM.
install_apt "PCManFM" "pcmanfm"
install_symlink_to ".config/pcmanfm/default/pcmanfm.conf"

# Install Emacs 24 and its config and theme.
install_apt "Emacs 24" "emacs24"
install_symlink_to ".emacs"
install_symlink_to ".emacs.d/themes/ample-zen-theme.el"

# Install Sublime Text 3 and its config and user commands.
URL="https://download.sublimetext.com/sublime-text_build-3126_amd64.deb"
download_and_install_deb "Sublime Text 3" "$URL"
USERDIR=".config/sublime-text-3/Packages/User"
install_symlink_to "$USERDIR/Anaconda.sublime-settings"
install_symlink_to "$USERDIR/Default (Linux).sublime-keymap"
install_symlink_to "$USERDIR/Preferences.sublime-settings"
install_symlink_to "$USERDIR/pylintrc"
install_symlink_to "$USERDIR/Python.sublime-settings"
install_symlink_to "$USERDIR/SublimeLinter.sublime-settings"
install_symlink_to "$USERDIR/show_keyboard_shortcuts.py"

# Install PulseAudio.
install_apt "PulseAudio" "pulseaudio pavucontrol"

# Install Thunderbird.
install_apt "Thunderbird" "thunderbird lightning calendar-google-provider"

# Install LibreOffice.
install_apt "LibreOffice" "libreoffice"

# Install VLC Media Player.
install_apt "VLC Media Player" "vlc"

# Install scrot.
install_apt "scrot" "scrot"

# Install GIMP.
install_apt "GIMP" "gimp"

# Install Qalculate!.
install_apt "Qalculate!" "qalculate"

# Install Deluge.
install_apt "Deluge" "deluge"
install_symlink_to ".config/deluge/core.conf"
install_symlink_to ".config/deluge/gtkui.conf"
