#!/usr/bin/env bash
# EasyTrac software/config installation module.

# Source utility functions.
SCRIPTSDIR="$(dirname "$(pwd)/$0")"
. "$SCRIPTSDIR/utils"

# Software installation.
software() {
  Q="Install EasyTrac? [y/n] "
  if ask "$Q"; then
    PKG="google-api-python-client google-auth-httplib2 google-auth-oauthlib"
    sudo apt install python3-pip
    sudo pip3 install $PKG
    install_symlink_to ".config/easytrac/easytrac.py"
  fi
}

# Config installation.
config() {
  return
}
