#!/usr/bin/env bash
# Google Chrome software/config installation module.

# Source utility functions.
SCRIPTSDIR="$(dirname "$(pwd)/$0")"
. "$SCRIPTSDIR/utils"

# Software installation.
software() {
  Q="Install Google Chrome? [y/n] "
  if ask "$Q"; then
    URL="https://dl.google.com/linux/direct"
    URL="$URL/google-chrome-stable_current_amd64.deb"
    download_and_install_deb "$URL"
  fi
}

# Config installation.
config() {
  return
}
