#!/usr/bin/env bash
# Deluge software/config installation module.

# Source utility functions.
SCRIPTSDIR="$(dirname "$(pwd)/$0")"
. "$SCRIPTSDIR/utils"

# Software installation.
software() {
  Q="Install Deluge? [y/n] "
  if ask "$Q"; then
    PKG="deluge"
    sudo apt install $PKG
  fi
}

# Config installation.
config() {
  Q="Install Deluge config? [y/n] "
  if ask "$Q"; then
    install_symlink_to ".config/deluge/core.conf"
    install_symlink_to ".config/deluge/gtkui.conf"
  fi
}
