#!/usr/bin/env bash
# pyFormex software/config installation module.

# Source utility functions.
SCRIPTSDIR="$(dirname "$(pwd)/$0")"
. "$SCRIPTSDIR/utils"

# Software installation.
software() {
  Q="Install pyFormex? [y/n] "
  if ask "$Q"; then
    # pyFormex dependencies.
    PKG="python-numpy python-opengl python-qt4 python-pyside"
    PKG="$PKG python-qt4-gl python-dev libglu1-mesa-dev libfreetype6-dev"
    PKG="$PKG python-matplotlib pkg-config libgts-dev libglib2.0-dev gcc"
    PKG="$PKG docutils-common admesh paraview vtk6 python-vtk6 vmtk python-vmtk"
    PKG="$PKG units python-scipy python-dicom"
    sudo apt-get install $PKG
    # pyFormex Git repository.
    read -rp "Username for 'ssh://git.feops.com': " USER
    REP="ssh://$USER@git.feops.com:1222/srv/git/pyformex.git"
    TGT="$HOME/Documents/pyformex"
    install_git_repo "$REP" "$TGT"
    # pyFormex extra's
    EXT="$TGT/pyformex/extra"
    if [ -d "$EXT" ]; then
      CWD=$(pwd)
      cd "$EXT/gts"
      sudo make all
      cd "$CWD"
    fi
  fi
}

# Config installation.
config() {
  Q="Install pyFormex config? [y/n] "
  if ask "$Q"; then
    install_symlink_to ".config/pyformex/pyformex.conf"
  fi
}
