#!/usr/bin/env bash
# PulseAudio software/config installation module.

# Source utility functions.
SCRIPTSDIR="$(dirname "$(pwd)/$0")"
. "$SCRIPTSDIR/utils"

# Software installation.
software() {
  Q="Install PulseAudio? [y/n] "
  if ask "$Q"; then
    PKG="pulseaudio pavucontrol"
    sudo apt-get install $PKG
  fi
}

# Config installation.
config() {
  return
}
