#!/usr/bin/env bash
# Qalculate! software/config installation module.

# Source utility functions.
SCRIPTSDIR="$(dirname "$(pwd)/$0")"
. "$SCRIPTSDIR/utils"

# Software installation.
software() {
  Q="Install Qalculate!? [y/n] "
  if ask "$Q"; then
    PKG="qalculate"
    sudo apt install $PKG
  fi
}

# Config installation.
config() {
  return
}
