#!/usr/bin/env bash
# LibreOffice software/config installation module.

# Source utility functions.
SCRIPTSDIR="$(dirname "$(pwd)/$0")"
. "$SCRIPTSDIR/utils"

# Software installation.
software() {
  Q="Install LibreOffice? [y/n] "
  if ask "$Q"; then
    PKG="libreoffice"
    sudo apt install $PKG
  fi
}

# Config installation.
config() {
  return
}
