#!/usr/bin/env bash

# Source utility functions.
SCRIPTSDIR="$(dirname "$(pwd)/$0")"
. "$SCRIPTSDIR/utils"

# Install pyFormex, its dependencies and its config.
REP="bumps:/srv/git/pyformex.git"
TGT="$HOME/Documents/pyformex"
CFG=".config/pyformex/pyformex.conf"
PKG="python-numpy python-opengl python-qt4 python-pyside"
PKG="$PKG python-qt4-gl python-dev libglu1-mesa-dev libfreetype6-dev"
PKG="$PKG python-matplotlib pkg-config libgts-dev libglib2.0-dev gcc"
PKG="$PKG docutils-common admesh paraview vtk6 python-vtk6 vmtk python-vmtk"
PKG="$PKG units python-scipy python-dicom"
install_apt "pyFormex dependencies" "$PKG"
install_git_repo "pyFormex" "$REP" "$TGT"
install_symlink_to "$CFG"

# Install TAVIguide-pp and its config.
REP="https://net.feops.com/gitlab/feops/TAVIguide-pp.git"
TGT="$HOME/Documents/feops/taviguide/taviguide-pp"
CFG=".config/pyformex/taviguide.conf"
install_git_repo "TAVIguide-pp" "$REP" "$TGT"
install_symlink_to "$CFG"

# Install MITRALguide-pp.
REP="https://net.feops.com/gitlab/feops/MITRALguide-pp.git"
TGT="$HOME/Documents/feops/mitralguide/mitralguide-pp"
install_git_repo "MITRALguide-pp" "$REP" "$TGT"
