#!/usr/bin/env bash
# TAVIguide-pp software/config installation module.

# Source utility functions.
SCRIPTSDIR="$(dirname "$(pwd)/$0")"
. "$SCRIPTSDIR/utils"

# Software installation.
software() {
  Q="Install TAVIguide-pp? [y/n] "
  if ask "$Q"; then
    read -rp "Username for 'https://net.feops.com': " USER
    REP="https://$USER@net.feops.com/gitlab/feops/TAVIguide-pp.git"
    TGT="$HOME/Documents/taviguide/taviguide-pp"
    install_git_repo "$REP" "$TGT"
  fi
}

# Config installation.
config() {
  Q="Install TAVIguide-pp config? [y/n] "
  if ask "$Q"; then
    install_symlink_to ".config/pyformex/taviguide.conf"
    install_symlink_to ".config/pyformex/taviguidepp.conf"
  fi
}
