#!/usr/bin/env bash
# pyFormex software/config installation module.

# Source utility functions.
SCRIPTSDIR="$(dirname "$(pwd)/$0")"
. "$SCRIPTSDIR/utils"

# Software installation.
software() {
  return
}

# Config installation.
config() {
  Q="Install pyFormex config? [y/n] "
  if ask "$Q"; then
    install_symlink_to ".config/pyformex/pyformex.conf"
    install_symlink_to ".config/pyformex/laaopp.conf"
    install_symlink_to ".config/pyformex/tavipp.conf"
  fi
}
