#!/usr/bin/env bash
# Sublime Text 3 software/config installation module.

# Source utility functions.
SCRIPTSDIR="$(dirname "$(pwd)/$0")"
. "$SCRIPTSDIR/utils"

# Software installation.
# See https://www.sublimetext.com/docs/3/linux_repositories.html
software() {
  Q="Install Sublime Text 3? [y/n] "
  if ask "$Q"; then
    KEY="https://download.sublimetext.com/sublimehq-pub.gpg"
    SRC="deb https://download.sublimetext.com/ apt/stable/"
    LST="/etc/apt/sources.list.d/sublime-text.list"
    PKG="sublime-text"
    wget -qO - "$KEY" | sudo apt-key add -
    echo "$SRC" | sudo tee "$LST"
    sudo apt-get update
    sudo apt-get install $PKG
  fi
}

# Config installation.
config() {
  Q="Install Sublime Text 3 config? [y/n] "
  if ask "$Q"; then
    STDIR=".config/sublime-text-3"
    # Package Control.
    IPDIR="$HOME/$STDIR/Installed Packages"
    PCTRL="$IPDIR/Package Control.sublime-package"
    if [ ! -e "$PCTRL" ]; then
      URL="https://packagecontrol.io/Package%20Control.sublime-package"
      wget -P "$IPDIR" "$URL"
    else
      echo "Sublime Text Package Control already installed."
    fi
    # Config files.
    USERDIR="$STDIR/Packages/User"
    install_symlink_to "$USERDIR/Package Control.sublime-settings"
    install_symlink_to "$USERDIR/Anaconda.sublime-settings"
    install_symlink_to "$USERDIR/Default (Linux).sublime-keymap"
    install_symlink_to "$USERDIR/Plain text.sublime-settings"
    install_symlink_to "$USERDIR/Preferences.sublime-settings"
    install_symlink_to "$USERDIR/pylintrc"
    install_symlink_to "$USERDIR/Python.sublime-settings"
    install_symlink_to "$USERDIR/SublimeLinter.sublime-settings"
    install_symlink_to "$USERDIR/show_keyboard_shortcuts.py"
    install_symlink_to "$USERDIR/SublimeLinter/Flatland Dark (SL).tmTheme"
  fi
}
