#!/usr/bin/env bash
# Git software/config installation module.

# Source utility functions.
SCRIPTSDIR="$(dirname "$(pwd)/$0")"
. "$SCRIPTSDIR/utils"

# Software installation.
software() {
  Q="Install Git and gitk? [y/n] "
  if ask "$Q"; then
    PKG="git gitk"
    sudo apt-get install $PKG
  fi
}

# Config installation.
config() {
  Q="Install Git config? [y/n] "
  if ask "$Q"; then
    install_symlink_to ".gitconfig"
  fi
}
