#!/usr/bin/env bash
# Emacs 24 software/config installation module.

# Source utility functions.
SCRIPTSDIR="$(dirname "$(pwd)/$0")"
. "$SCRIPTSDIR/utils"

# Software installation.
software() {
  Q="Install Emacs 24? [y/n] "
  if ask "$Q"; then
    PKG="emacs24"
    sudo apt-get install $PKG
  fi
}

# Config installation.
config() {
  Q="Install Emacs 24 config? [y/n] "
  if ask "$Q"; then
    install_symlink_to ".emacs"
    install_symlink_to ".emacs.d/themes/ample-zen-theme.el"
  fi
}
