#!/usr/bin/env bash

# Get '.dotfiles/config' directory.
SCRIPTSDIR="$(dirname "$(pwd)/$0")"
CFGDIR="$(realpath "$SCRIPTSDIR/../config")"

# Ask a yes/no question. Returns 0 for yes, 1 for no.
ask() {
  while true; do
    read -rn 1 -p "$1"
    if [ ! -z "$REPLY" ]; then # No blank line after ENTER.
      echo
    fi
    if [[ "${REPLY,,}" == y* ]]; then
      return 0
    fi
    if [[ "${REPLY,,}" == n* ]]; then
      return 1
    fi
    echo "Please answer [y]es or [n]o."
  done
}

# Create a symlink to a config file.
# If link name exists, it is backed up (with datetime) to ~/.dotfilesbak.
install_symlink_to() {
  TARGET="$CFGDIR/$1"
  LINKNAME="$HOME/$1"
  if [ -e "$LINKNAME" ]; then
    BAKDIR="$HOME/.dotfilesbak"
    BASENAME="$(basename "$LINKNAME")"
    DATETIME="$(date +%Y%m%d%H%M%S)"
    mkdir -pv "$BAKDIR"
    mv -v "$LINKNAME" "$BAKDIR/$BASENAME-$DATETIME"
  fi
  mkdir -pv "$(dirname "$LINKNAME")"
  ln -sfv "$TARGET" "$LINKNAME"
}

# Download and install a .deb file.
# Also attempts to fix missing dependencies.
# The .deb file is removed after installation.
download_and_install_deb() {
  wget -P "/tmp" "$1"
  DEB="/tmp/$(basename "$1")"
  sudo dpkg -i "$DEB"
  sudo apt-get -f install
  rm -rvf "$DEB"
}

# Clone a GIT repository.
# Repositories are only cloned if the target directory doesn't exist.
install_git_repo() {
  if [ ! -e "$2" ]; then
    git clone "$1" "$2"
  else
    echo "Did not clone '$1' into '$2'."
    echo "Directory or file '$2' already exists."
  fi
}
